### ISSUE TITLE
[Enhancement] Create valid favicons for phones. Make it look like a native "app"

### ISSUE THREAD

**Issue by Paul00O** [aureleoules/epitaf#21]
Not really an issue but could be cool if the favicons were generated for ALL devices.
For exemple on iPhone you could "extract" the website to make it look like a native app on the IOS home menu using safari.
Sadly the icon for the app looks like shit since you DID NOT generated/set one.
Instead of creating every icons by hand there is a bunch of websites who do it for you. For exemple https://realfavicongenerator.net/ it create it for windows metro, IOS, android, macOS, etc...

**Comment by V-Paul00** [comment]
> Hello, Thank you for your suggestion! Could I let you add this feature? The original logo is located at `ui/public/logo.png`.

Just created a pull request.
