### ISSUE TITLE
Assignation de Semestre/Classe/Région avec assistant (ex: YAKA)

### ISSUE THREAD

**Issue by Alex-Leme** [aureleoules/epitaf#28]
Petit bug avec les infos du profil affichées pour les assistants, soit cela vient de l'API avec la BDD du cri, soit d'une feature non finie ou testée ?
![image](https://user-images.githubusercontent.com/46632029/146777011-a985701e-1a92-4464-b8c2-dc2b8bd7acb8.png)

**Comment by aureleoules** [comment]
Fixed
