### ISSUE TITLE
UI/UX discussion

### ISSUE THREAD

**Issue by Vinetos** [aureleoules/epitaf#8]
I want to open a discussion about the design.
Isn't easier to read if the title of the Homework is the Big title of the element and the course's name in bottom ?

Here is an modified example :

![image](https://user-images.githubusercontent.com/10145351/100348391-233bbb00-2fe7-11eb-8655-1930342cf704.png)

What are you guys thinking ?

**Comment by aureleoules** [comment]
I think you're right, it makes more sense

**Comment by aureleoules** [comment]
i fixed it
